export const navlinks = [
   {
      name: "Home",
      path: "/",
   },
   {
      name: "About",
      path: "/about",
   },
   {
      name: "Contact",
      path: "/contact",
   },
   {
      name: "Cart",
      path: "/cart",
   },
];

export const products = [
   {
      id: 1,
      name: "Earthen Bottle",
      href: "#",
      price: 48,
      imageSrc: "https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-01.jpg",
      imageAlt: "Tall slender porcelain bottle with natural clay textured body and cork stopper.",
   },
   {
      id: 2,
      name: "Wooden Desk Organizer",
      href: "#",
      price: 35,
      imageSrc: "https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-02.jpg",
      imageAlt: "A wooden desk organizer with various compartments for office supplies.",
   },
   {
      id: 3,
      name: "Ceramic Mug",
      href: "#",
      price: 18,
      imageSrc: "https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-03.jpg",
      imageAlt: "A classic white ceramic mug with a simple design.",
   },
   {
      id: 4,
      name: "Leather Wallet",
      href: "#",
      price: 60,
      imageSrc: "https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-04.jpg",
      imageAlt: "A brown leather wallet with multiple compartments for cards and cash.",
   },
   {
      id: 5,
      name: "Glass Vase",
      href: "#",
      price: 22,
      imageSrc: "https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-05.jpg",
      imageAlt: "A clear glass vase with a minimalist design.",
   },
   {
      id: 6,
      name: "Metal Pen Holder",
      href: "#",
      price: 15,
      imageSrc: "https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-06.jpg",
      imageAlt: "A sleek metal pen holder with a modern design.",
   },
   {
      id: 7,
      name: "Cotton Throw Blanket",
      href: "#",
      price: 40,
      imageSrc: "https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-07.jpg",
      imageAlt: "A soft cotton throw blanket in a neutral color.",
   },
   {
      id: 8,
      name: "Wooden Picture Frame",
      href: "#",
      price: 25,
      imageSrc: "https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-08.jpg",
      imageAlt: "A wooden picture frame with a classic design.",
   },
   {
      id: 9,
      name: "Stainless Steel Bottle",
      href: "#",
      price: 30,
      imageSrc: "https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-05.jpg",
      imageAlt: "A stainless steel bottle with a sleek design.",
   },
   {
      id: 10,
      name: "Woven Basket",
      href: "#",
      price: 20,
      imageSrc: "https://tailwindui.com/img/ecommerce-images/category-page-04-image-card-08.jpg",
      imageAlt: "A handwoven basket perfect for storage and decoration.",
   },
];
